services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

  adminpanel:
    build: ./admin-panel
    ports:
      - "3001:3001"
    depends_on:
      - server
    restart: always

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/forms
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
